# Generated by Django 5.0.2 on 2024-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='drive_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
