# Generated by Django 5.0.2 on 2024-03-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_module_drive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.CharField(choices=[('s1', 's1'), ('s2', 's2'), ('s3', 's3'), ('s4', 's4'), ('s5', 's5'), ('s6', 's6'), ('s7', 's7'), ('s8', 's8'), ('s9', 's9'), ('s10', 's10')], max_length=10, null=True),
        ),
    ]
